"""users profile flags, messages sender_id/time/fk, gin index

Revision ID: 45c5351c41f0
Revises: dbbeabad988e
Create Date: 2026-10-09 21:27:31.291978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45c5351c41f0'
down_revision: Union[str, None] = 'dbbeabad988e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('chats', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('chats', 'users',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=False)
    op.drop_index('ix_chats_id', table_name='chats')
    op.create_index('ix_chats_users_gin', 'chats', ['users'], unique=False, postgresql_using='gin')
    op.add_column('files', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('files', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('files', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_files_id', table_name='files')
    op.create_index(op.f('ix_files_file_path'), 'files', ['file_path'], unique=False)
    # user_from_id -> sender_id (rename сохраняет данные)
    op.alter_column('messages', 'user_from_id',
               new_column_name='sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('messages', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('messages', 'time',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="to_timestamp(time, 'YYYY MM DD HH24 MI SS')",
               nullable=False)
    op.alter_column('messages', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_messages_id', table_name='messages')
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_messages_message_file_id'), 'messages', ['message_file_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_messages_time'), 'messages', ['time'], unique=False)
    op.create_foreign_key('fk_messages_chat_id_chats', 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_messages_message_file_id_files', 'messages', 'files', ['message_file_id'], ['id'])
    op.create_foreign_key('fk_messages_sender_id_users', 'messages', 'users', ['sender_id'], ['id'])
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_users_id', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'is_active')
    op.drop_constraint('fk_messages_sender_id_users', 'messages', type_='foreignkey')
    op.drop_constraint('fk_messages_message_file_id_files', 'messages', type_='foreignkey')
    op.drop_constraint('fk_messages_chat_id_chats', 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_time'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_file_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.create_index('ix_messages_id', 'messages', ['id'], unique=False)
    op.alter_column('messages', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('messages', 'time',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               postgresql_using='time::text',
               nullable=True)
    op.drop_column('messages', 'updated_at')
    op.drop_column('messages', 'created_at')
    # sender_id -> user_from_id (обратное переименование)
    op.alter_column('messages', 'sender_id',
               new_column_name='user_from_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_files_file_path'), table_name='files')
    op.create_index('ix_files_id', 'files', ['id'], unique=False)
    op.alter_column('files', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('files', 'updated_at')
    op.drop_column('files', 'created_at')
    op.drop_index('ix_chats_users_gin', table_name='chats', postgresql_using='gin')
    op.create_index('ix_chats_id', 'chats', ['id'], unique=False)
    op.alter_column('chats', 'users',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=True)
    op.drop_column('chats', 'updated_at')
    op.drop_column('chats', 'created_at')
    # ### end Alembic commands ###
